
if(typeof JSON!=='object'){JSON={};}
(function(){'use strict';function f(n){return n<10?'0'+n:n;}
    if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
        f(this.getUTCMonth()+1)+'-'+
        f(this.getUTCDate())+'T'+
        f(this.getUTCHours())+':'+
        f(this.getUTCMinutes())+':'+
        f(this.getUTCSeconds())+'Z':null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();};}
    var cx,escapable,gap,indent,meta,rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
    function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
        if(typeof rep==='function'){value=rep.call(holder,key,value);}
        switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
            gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
                v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}
            if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==='string'){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
            v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
    if(typeof JSON.stringify!=='function'){escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
        rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
        return str('',{'':value});};}}());

var LiveAgentTrackerXD=function(){var interval_id,last_hash,cache_bust=1,window=this;var ieVersion=-1;if(navigator.appName=='Microsoft Internet Explorer'){var ua=navigator.userAgent;var re=new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");if(re.exec(ua)!=null){ieVersion=parseFloat(RegExp.$1);if(document.documentMode<8){ieVersion=7;}}}
    var regex=new RegExp("[\\?&]ie=([^&#]*)");var results=regex.exec(window.location.href);if(results!=null){ieVersion=results[1];}
    return{getIeVersion:function(){return ieVersion;},postMessage:function(args,target_url,target){if(!target_url){return;}
        if(typeof args==='string'){var message=args;}else{var message=args[0]+'(';for(var i=1;i<args.length;i++){var value=args[i];if(typeof value==='string'){value="'"+value.replace(/'/g,"\\'")+"'";}
            message+=(i>1?', ':'')+value;}
            message+=')';}
        target=target||parent;if(ieVersion!=7&&window['postMessage']){target['postMessage'](message,'*');}else if(target_url){target.location=target_url.replace(/#.*$/,'')+'#'+(+new Date)+(cache_bust++)+'&'+message;}},receiveMessage:function(instance){var callback=function(message){try{eval(instance+'.'+message.data+";");}catch(e){}};if(ieVersion!=7&&window['postMessage']){if(window['addEventListener']){window[callback?'addEventListener':'removeEventListener']('message',callback,!1);}else{window[callback?'attachEvent':'detachEvent']('onmessage',callback);}}else{interval_id&&clearInterval(interval_id);interval_id=null;if(callback){interval_id=setInterval(function(){var hash=document.location.hash;if(hash===last_hash){return;}
        re=/^#?\d+&/;if(re.test(hash)){callback({data:hash.replace(re,'')});document.location.hash='';}
        last_hash=document.location.hash;},100);}}}};}();

(function(window,document){"use strict;"
    if(window.LiveAgent){return;}
    var $class=function(def){var construct=def.hasOwnProperty('construct')?def.construct:function(){};for(var name in $class.Initializers){$class.Initializers[name].call(construct,def[name],def);}
        return construct;};$class.Initializers={Extends:function(parent){if(parent){var F=function(){};this._superClass=F.prototype=parent.prototype;this.prototype=new F;}},Mixins:function(mixins,def){this.mixin=function(mixin){for(var key in mixin){if(key in $class.Initializers)continue;this.prototype[key]=mixin[key];}
        this.prototype.construct=this;};var objects=[def].concat(mixins||[]);for(var i=0,l=objects.length;i<l;i++){this.mixin(objects[i]);}}};var Request=$class({construct:function(className){this.params={};this.add('C',className);},add:function(name,value){this.params[name]=value;},fullEncodeUrl_:function(url){if(url==null||url==""){return'';}
        url=url.replace(new RegExp("http://",'g'),"__H__");url=url.replace(new RegExp("https://",'g'),"__S__");return url;},getParamsString:function(){var paramsString="";for(var key in this.params){if(this.params.hasOwnProperty(key)){paramsString+="&"+key+"="+encodeURIComponent(this.params[key]);}}
        return paramsString;}});var TrackVisit=$class({Extends:Request,construct:function(){Request.call(this,'Track');this.add('B',LiveAgent.instance.getBrowserId());this.add('S',LiveAgent.instance.getSessionId());this.add('pt',this.getTitle_());this.add('url',this.fullEncodeUrl_(document.location.href));this.add('ref',this.fullEncodeUrl_(document.referrer));this.add('sr',screen.width+'x'+screen.height);this.add('ud',JSON.stringify(LiveAgent.instance.getUserDetails()));this.add('vn',LiveAgent.getCookie('LaVisitorNew'));this.add('ci',LiveAgent.getCookie('closedInvitations'));},getTitle_:function(){var title=document.title;if(typeof(document.title)=="string"){title=document.title.replace(/\|/g," ");}
        return title;}});var Invite=$class({Extends:Request,construct:function(invitationId){Request.call(this,'Invite');this.add('id',invitationId);this.add('url',this.fullEncodeUrl_(document.location.href));}});var LiveAgent=$class({integrationElementId:'la_x2s6df8d',construct:function(){this.serverUrl=this.computeServerUrl_();this.sessionId='';this.browserId=LiveAgent.getCookie('LaVisitorId');this.tracking=true;this.tracker=null;this.requests=[];this.elements=[];this.widgets=[];this.invitations=[];this.openedWidget=null;this.userDetails=null;this.pageOpenedTimestamp=new Date().getTime();this.isMobileBrowser=false;this.runningChatEnabled=true;this.initBrowserId_();this.initSessionId_();this.initUserDetails_();this.detectMobileBrowser_();setTimeout(function(){LiveAgent.instance.trackVisit_();},250);LiveAgentTrackerXD.receiveMessage('LiveAgent.instance');this.initCursorPositionTracking_();setTimeout(function(){LiveAgent.instance.initRunningChat_();},250);},tracker:null,initTracker:function(tracker){this.tracker=tracker;},getWidget:function(elementId){return this.elements[elementId];},getAllWidget:function(widgetId){return this.widgets[widgetId];},createInvitation:function(id,timeOnPage){if(LiveAgent.getCookie('closedInvitations').indexOf(id)>=0){return;}
        return this.invitations.push(this.addWidget_(new LiveAgent.Invitation(id,timeOnPage)));},addInvitationForPull:function(id,timeOnPage,matchFunction){if(this.invitations.length>0){return}
        if(LiveAgent.getCookie('closedInvitations').indexOf(id)>=0){return;}
        try{if(!matchFunction(LiveAgent.getCookie('LaVisitorNew'),document.location.href,document.referrer)){return;}}catch(e){return;}
        this.createInvitation(id,timeOnPage);},createManualInvitation:function(id,cid){return this.addWidget_(new LiveAgent.ManualInvitation(id,cid));},addWidget_:function(widget){if(this.widgets[widget.getId()]==undefined){this.widgets[widget.getId()]=[];}
        this.widgets[widget.getId()].push(widget);this.elements[widget.getElementId()]=widget;return widget;},removeWidget:function(widgetId){if(this.widgets[widgetId]==undefined){return;}
        delete this.elements[widgetId];delete this.widgets[widgetId];},enqueue:function(request){this.requests[this.requests.length]=request.params;},send:function(request){this.enqueue(request);clearTimeout(this.sendTimer);this.sendTimer=setTimeout(function(){LiveAgent.instance.sendRequest_()},300);},getPageOpenedTimestamp:function(){return this.pageOpenedTimestamp;},getSessionId:function(){return this.sessionId;},getBrowserId:function(){return this.browserId;},isMobile:function(){return this.isMobileBrowser;},getPageCharset:function(){return(document.characterSet)?document.characterSet:document.charset;},getUserDetails:function(){return this.userDetails;},getCursorPosition:function(){return this.cursorPosition;},getServerUrl:function(specProtocol){var serverProtocolUrl=this.serverUrl;if(typeof specProtocol!=="undefined"){serverProtocolUrl=specProtocol+this.removeUrlProtocol_(this.serverUrl);}
        return serverProtocolUrl;},trackVisit_:function(){if(!this.tracking){return;}
        var request=new TrackVisit();this.addScript('scripts/track_visit.php?t=Y'+request.getParamsString());},getRequestsParams_:function(){return'?S='+this.sessionId
        +'&B='+this.browserId
        +'&ChS='+this.getPageCharset()
        +'&D='+encodeURIComponent(LiveAgent.stringifyToJSON(this.requests));},sendRequest_:function(){this.addScript('scripts/track.php'+this.getRequestsParams_());this.requests=[];},addScript:function(relativeUrl){var headTag=document.getElementsByTagName("head").item(0);var scriptTag=document.createElement("script");scriptTag.setAttribute("type","text/javascript");scriptTag.setAttribute("src",this.serverUrl+relativeUrl);headTag.appendChild(scriptTag);scriptTag.onload=scriptTag.onreadystatechange=function(){setTimeout(function(){try{headTag.removeChild(scriptTag);}catch(e){}},500);}},computeServerUrl_:function(specProtocol){var url=new String(document.getElementById(this.integrationElementId).src);if(url.substr(0,1)=='/'&&url.substr(1,1)!='/'){url=document.location.protocol+'//'
        +document.location.host+url;}
        return url.substr(0,url.lastIndexOf('scripts/'));},removeUrlProtocol_:function(serverUrl){var url=new String(serverUrl);if(url.substr(0,5)=='http:'){return url.substr(5);}
        if(url.substr(0,6)=='https:'){return url.substr(6);}
        return $url;},hasOpenedWidget:function(){return this.openedWidget!=null;},setOpenedWidget:function(button){this.openedWidget=button;this.clearInvitations_();},clearInvitations_:function(){var invitationsLength=this.invitations.length;for(var i=0;i<invitationsLength;i++){this.invitations[i].cancel();}
        this.invitations=[];},initCursorPositionTracking_:function(){this.setCursorPosition_(0,0);var me=this;if(!document.all){document.captureEvents(Event.MOUSEMOVE);document.onmousemove=function(e){me.setCursorPosition_(e.pageX,e.pageY);}
        return;}
        document.onmousemove=function(e){me.setCursorPosition_(event.clientX+document.body.scrollLeft,event.clientY+document.body.scrollTop);};},setCursorPosition_:function(cursorX,cursorY){this.cursorPosition={x:Math.max(0,cursorX),y:Math.max(0,cursorY)};},getWindowSize_:function(){var wWidth=0,wHeight=0;if(typeof(window.innerWidth)=='number'){wWidth=window.innerWidth;wHeight=window.innerHeight;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){wWidth=document.documentElement.clientWidth;wHeight=document.documentElement.clientHeight;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){wWidth=document.body.clientWidth;wHeight=document.body.clientHeight;}
        return{width:wWidth,height:wHeight};},createPopoutWindowParams_:function(width,height,position){var windowSize=this.getWindowSize_();if(width>windowSize.width){width=windowSize.width;}
        if(height>windowSize.height){height=windowSize.height;}
        var left=0;var top=windowSize.height/2-height/2;if(position=='R'){left=windowSize.width-width;}else if(position=='C'){left=windowSize.width/2-width/2;}else if(position=='O'){var cursor=this.getCursorPosition();left=cursor.x;top=cursor.y;}
        return'width='+width+',height='+height+',left='+Math.round(left)+',top='
            +Math.round(top)+',scrollbars=yes';},getServerDomain_:function(){var link=document.createElement('a');link.href=this.serverUrl;return link.host+link.pathname;},closeOpenedWidget:function(){if(!this.hasOpenedWidget()){return;}
        this.openedWidget.hide();this.setOpenedWidget(null);LiveAgent.setCookie('LaRunningChat','');},minimizeOpenedWidget:function(newHeight){if(!this.hasOpenedWidget()){return;}
        if(this.openedWidget.getPosition()=="DR"||this.openedWidget.getPosition()=="DL"){if(newHeight>150){this.openedWidget.getElement().style.top="0";this.openedWidget.getElement().style.height="100%";}else{this.openedWidget.getElement().style.top="auto";this.openedWidget.setSize(this.openedWidget.width,newHeight);}}else{this.openedWidget.setSize(this.openedWidget.width,newHeight);}},clickVirtualButton:function(bid){if(this.elements[bid]==null){return;}
        this.elements[bid].onClick();},onEmbeddedChatOpened:function(cid){if(cid==''){return;}
        var cookie=LiveAgent.getCookie('LaRunningChat');if(cookie!=null&&cookie!=''){return;}
        if(!this.hasOpenedWidget()){return;}
        var preset=this.openedWidget.getRunningChatPreset();preset.cid=cid;preset.domain=this.getServerDomain_();var runChat=LiveAgent.stringifyToJSON(preset);if(runChat!=''){LiveAgent.setCookie('LaRunningChat',runChat);}},startChatFromContactForm:function(cid){if(!this.hasOpenedWidget()){return;}
        this.openedWidget.startChat(cid);},initUserDetails_:function(){try{this.userDetails=JSON.parse(LiveAgent.getCookie('LaUserDetails'));}catch(e){this.userDetails={};}
        if(!typeof(this.userDetails)=='object'){this.userDetails={};}},initRunningChat_:function(){var cookie=LiveAgent.getCookie('LaRunningChat');if(cookie==null||cookie==''||!this.runningChatEnabled){return;}
        var preset=JSON.parse(decodeURIComponent(cookie));if(preset.domain!==this.getServerDomain_()){return;}
        var cwid=this.parseContactWidgetIdFromUrl_(preset.url);var onCloseFunction=function(){};if(cwid!=null){var wdgts=this.getAllWidget(cwid);if(wdgts!=undefined){for(var i=0;i<wdgts.length;i++){if(wdgts[i]instanceof LiveAgent.Button){wdgts[i].hideButton_();}}
            onCloseFunction=function(){for(var i=0;i<wdgts.length;i++){if(wdgts[i]instanceof LiveAgent.Button){wdgts[i].onCloseFunction_();}}};}}
        this.openedWidget=new LiveAgent.RunningChat(preset);this.openedWidget.show(onCloseFunction);},parseContactWidgetIdFromUrl_:function(url){var re=/.*[?&]cwid=([a-z0-9]{8})&.*/gmi;var match;if((match=re.exec(url))!==null){return match[1];}
        return null;},detectMobileBrowser_:function(){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4))){this.isMobileBrowser=true;}},initSessionId_:function(id){this.sessionId=LiveAgent.getCookie('LaSID');if(this.sessionId==''){this.sessionId=this.generateRandomId_();}
        LiveAgent.setCookie('LaSID',this.sessionId);},initBrowserId_:function(){this.browserId=LiveAgent.getCookie('LaVisitorId');if(this.browserId==''){LiveAgent.setCookie('LaVisitorNew','Y',1);this.browserId=this.generateRandomId_();}
        LiveAgent.setCookie('LaVisitorId',this.browserId,30);},generateRandomId_:function(){var d=new Date().getTime();var uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'.replace(/[x]/g,function(c){var r=(d+Math.random()*36)%36|0;d=Math.floor(d/16);return r.toString(36);});return uuid;}});LiveAgent.getCookie=function(name){var value="; "+document.cookie;var parts=value.split("; "+name+"=");if(parts.length==2){return parts.pop().split(";").shift();}
        return'';};LiveAgent.setCookie=function(name,value,expireDays){var expireString='';if(typeof expireDays!=='undefined'){var exdate=new Date();exdate.setDate(exdate.getDate()+expireDays);expireString="; expires="+exdate.toUTCString();}
        document.cookie=name+"="+escape(value)+"; path=/"
            +expireString;};LiveAgent.stringifyToJSON=function(value){var _json_stringify=JSON.stringify;JSON.stringify=function(value){var _array_tojson=Array.prototype.toJSON;if(_array_tojson!=undefined){delete Array.prototype.toJSON;}
        var r=_json_stringify(value);if(_array_tojson!=undefined){Array.prototype.toJSON=_array_tojson;}
        return r;};var string=JSON.stringify(value);JSON.stringify=_json_stringify;return string;}
    LiveAgent.disableTracking=function(){LiveAgent.instance.tracking=false;};LiveAgent.createButton=function(bid,element,note){return LiveAgent.instance.addWidget_(new LiveAgent.Button(bid,element,note));};LiveAgent.createVirtualButton=function(bid,element,note){return LiveAgent.instance.addWidget_(new LiveAgent.VirtualButton(bid,element,note));};LiveAgent.createForm=function(fid,element,note){return LiveAgent.instance.addWidget_(new LiveAgent.InPageForm(fid,element,note));};LiveAgent.createKbSearchWidget=function(id){return LiveAgent.instance.addWidget_(new LiveAgent.KbSearchWidget(id));};LiveAgent.createKbChat=function(bid,cid){return LiveAgent.instance.addWidget_(new LiveAgent.KbChat(bid,cid));};LiveAgent.setUserDetails=function(email,firstName,lastName,phone){LiveAgent.addUserDetail('email',email);LiveAgent.addUserDetail('firstName',firstName);LiveAgent.addUserDetail('lastName',lastName);LiveAgent.addUserDetail('phone',phone);};LiveAgent.addField=function(key,value,prefix){if(key==''||key==null||value==''||value==null){return;}
        LiveAgent.instance.userDetails[prefix+key]=value;LiveAgent.setCookie('LaUserDetails',JSON.stringify(LiveAgent.instance.userDetails));};LiveAgent.addUserDetail=function(key,value){LiveAgent.addField(key,value,'');};LiveAgent.addContactField=function(key,value){LiveAgent.addField(key,value,'c_');};LiveAgent.addTicketField=function(key,value){LiveAgent.addField(key,value,'t_');};LiveAgent.loginUserOnServer=function(authHash){LiveAgent.RemoteAuth.login(authHash);};LiveAgent.logoutUserOnServer=function(authHash){LiveAgent.RemoteAuth.logout(authHash);};LiveAgent.disableRunningChat=function(){LiveAgent.instance.runningChatEnabled=false;};LiveAgent.Request=Request;LiveAgent.$class=$class;window.LiveAgent=LiveAgent;window.LiveAgentTracker=window.LiveAgent;window.LiveAgent.instance=new LiveAgent();LiveAgentTracker.disableOnlineVisitorsTracking=function(){LiveAgent.disableTracking();};LiveAgentTracker.closeBubbleButton=function(buttonId){LiveAgent.instance.getWidget(buttonId).closeBubble();};})(window,document);

(function($){if($.Iframe){return;}
    var Iframe=$.$class({construct:function(url){this.url=url;this.autoPrepareNextFrame=true;this.onCloseFunctions=[];this.init_();},show:function(params,onCloseFunction){this.addOnCloseFunction(onCloseFunction);if(!this.isLoaded){var me=this;this.onLoad_=function(){me.showFrame_(params)};return;}
        this.showFrame_(params);},hide:function(){this.element.style.display='none';var elementToDestroy=this.element;setTimeout(function(){elementToDestroy.parentNode.removeChild(elementToDestroy);},5000);if(this.autoPrepareNextFrame){this.init_();}
        this.onCloseFunctions.forEach(function(entry){entry();})},addOnCloseFunction:function(onCloseFunc){this.onCloseFunctions.push(onCloseFunc);},postMessage:function(message){LiveAgentTrackerXD.postMessage(message,this.element.src,this.frameXDReference);},setPosition:function(position,width,height){this.windowPosition=position;var style=this.element.style;if(position=='BR'){style.bottom='0px';style.right='0px';style.marginRight='2px';}else if(position=='BL'){style.bottom='0px';style.left='0px';style.marginLeft='2px';}else if(position=='TR'){style.top='0px';style.right='0px';style.smarginRight='2px';}else if(position=='TL'){style.top='0px';style.left='0px';style.marginLeft='2px';}else if(position=='DR'){style.top='0px';style.right='0px';style.bottom='0px';style.position='fixed';style.height='100%';}else if(position=='DL'){style.top='0px';style.left='0px';style.bottom='0px';style.position='fixed';style.height='100%';}else{style.top='50%';style.left='50%';style.marginLeft="-"+Math.round(width/2)+"px";style.marginTop="-"+Math.round(height/2)+"px";}},getPosition:function(){return this.windowPosition;},getElement:function(){return this.element;},setSize:function(width,height){var style=this.element.style;style.width=width+'px';style.height=height+'px';},setZIndex:function(zIndex){this.element.style.zIndex=zIndex;},init_:function(){this.isLoaded=false;this.windowPosition=false;this.onLoad_=function(){};this.element=document.createElement('iframe');var me=this;var onLoadFunction=function(){me.isLoaded=true;me.onLoad_();}
        if(this.element.attachEvent){this.element.attachEvent('onload',onLoadFunction);}else{this.element.onload=onLoadFunction;}
        var style=this.element.style;style.display='none';style.position='fixed';style.border='0px';style.overflow='hidden';this.element.setAttribute('src',this.url);this.element.setAttribute('allowfullscreen',true);if(typeof this.className!=="undefined"){this.element.setAttribute('class',this.className);}
        if(typeof this.id!=="undefined"){this.element.setAttribute('id',this.id);}
        document.body.appendChild(this.element);this.frameXDReference=frames[frames.length-1];},onLoad_:function(){},showFrame_:function(params){this.element.style.display='block';}});$.Iframe=Iframe;})(LiveAgent);

(function($){if($.EmbeddedChat){return;}
    var EmbeddedChat=$.$class({Extends:$.Iframe,construct:function(widgetUrl,width,height,position,zIndex,cwid){this.width=width;this.height=height;this.position=position;this.className="i-embedded-chat";this.id="ic"+cwid;if(zIndex==undefined||zIndex.trim()==""){zIndex='999997';}
        this.zIndex=zIndex;this.runningChatPreset={url:widgetUrl,width:width,height:height,position:position};var url=$.instance.getServerUrl()+widgetUrl
            +"&ie="+encodeURIComponent(LiveAgentTrackerXD.getIeVersion())
            +"&pt="+encodeURIComponent(document.title)
            +"#"+encodeURIComponent(document.location.href);$.Iframe.call(this,url);},getRunningChatPreset:function(){return this.runningChatPreset;},startChat:function(cidParam,onCloseFunction){this.show({cid:cidParam},onCloseFunction);},showFrame_:function(params){this.setZIndex(this.zIndex);this.setSize(this.width,this.height);this.setPosition(this.position,this.width,this.height);this.postMessage(['setParam','visitorId',LiveAgent.instance.getBrowserId()]);this.postMessage(['setParam','user_details',JSON.stringify($.instance.getUserDetails())]);for(var key in params){if(params.hasOwnProperty(key)){if(key=='cid'){continue;}
        this.postMessage(['setParam',key,params[key]]);}}
        if(params.cid!=undefined){this.postMessage(['start',params.cid]);}else{this.postMessage(['start']);}
        EmbeddedChat._superClass.showFrame_.call(this,params);$.instance.setOpenedWidget(this);}});$.EmbeddedChat=EmbeddedChat;})(LiveAgent);

(function($){if($.RunningChat){return;}
    var RunningChat=$.$class({Extends:$.EmbeddedChat,construct:function(preset){var url=preset.url.replace("_chat.html","_chatrunning.html")+"&cid="+preset.cid;$.EmbeddedChat.call(this,url,preset.width,preset.height,preset.position);},show:function(onCloseFunction){RunningChat._superClass.show.call(this,{},onCloseFunction);}});$.RunningChat=RunningChat;})(LiveAgent);

(function($){if($.PopupWidget){return;}
    var PopupWidget=$.$class({construct:function(widgetUrl,width,height,position,specProtocol){this.width=width;this.height=height;this.position=position;this.url=$.instance.getServerUrl(specProtocol)+widgetUrl;if($.instance.getBrowserId()!=undefined&&$.instance.getBrowserId()!=''){this.url+='&vid='+encodeURIComponent($.instance.getBrowserId());}
        if($.instance.getUserDetails()!=undefined&&JSON.stringify($.instance.getUserDetails()!='')){this.url+='&ud='+encodeURIComponent(JSON.stringify($.instance.getUserDetails()))}},show:function(params,onCloseFunction){this.onCloseFunction=onCloseFunction;if(params.note!=undefined&&params.note!=''){this.url+='&note='+encodeURIComponent(params.note);}
        this.openPopupWindow_(this.url);$.instance.setOpenedWidget(this);},hide:function(){if(this.onCloseFunction!=undefined){this.onCloseFunction();}},openPopupWindow_:function(serverUrl){serverUrl+="&pt="+encodeURIComponent(document.title)+"&ref="+encodeURIComponent(document.location.href);if(this.width==undefined){window.open(serverUrl,"_blank");}else{window.open(serverUrl,"_blank",$.instance.createPopoutWindowParams_(this.width,this.height,this.position));}},});$.PopupWidget=PopupWidget;})(LiveAgent);

(function($){if($.PopupChat){return;}
    var PopupChat=$.$class({Extends:$.PopupWidget,construct:function(widgetUrl,width,height,position){$.PopupWidget.call(this,widgetUrl,width,height,position,undefined);},startChat:function(cid,onCloseFunction){this.openPopupWindow_(this.url+'&cid='+cid,onCloseFunction);},});$.PopupChat=PopupChat;})(LiveAgent);

(function($){if($.Widget){return;}
    var Widget=$.$class({construct:function(id){this.id=id;this.elementId=this.buildElementId(id);this.sendInitRequest_();},isInitialized:function(){return this.dateChanged!=undefined;},initDateChanged:function(dateChanged){this.dateChanged=dateChanged;},sendInitRequest_:function(){var request=this.getCreateRequest();$.instance.addScript('scripts/button.php?ChS='+escape($.instance.getPageCharset())
        +request.getParamsString());},addButtonParamsToUrl_:function(url){return url;},getCreateRequest:function(){var request=new $.Request('Widget');request.add('i',this.id);request.add('p',request.fullEncodeUrl_(document.location.href));if($.instance.isMobile()){request.add('m','Y');}
        return request;},buildElementId:function(id){return"b_"+id+"_"+Math.round((Math.random()*1000)).toString();},getElementId:function(){return this.elementId;},getId:function(){return this.id;}});$.Widget=Widget;})(LiveAgent);

(function($){if($.EmbeddedForm){return;}
    var EmbeddedForm=$.$class({Extends:$.Iframe,construct:function(widgetUrl,width,height,position,zIndex,useBlocker,specProtocol,cwid){this.width=width;this.height=height;this.position=position;this.className="i-embedded-form";this.id="if"+cwid;this.useBlocker=useBlocker;if(zIndex==undefined||zIndex.trim()==""){zIndex='999997';}
        this.zIndex=zIndex;var url=$.instance.getServerUrl(specProtocol)+widgetUrl
            +"&ie="+encodeURIComponent(LiveAgentTrackerXD.getIeVersion())
            +"&pt="+encodeURIComponent(document.title)
            +"#"+encodeURIComponent(document.location.href)
        $.Iframe.call(this,url);if(this.useBlocker){this.initBlockingElement_();}},showFrame_:function(params){if(this.useBlocker){this.showBlockingElement_();}
        this.updateFrameStyle_();this.postMessage(['setParam','visitorId',LiveAgent.instance.getBrowserId()]);this.postMessage(['setParam','note',params.note]);this.postMessage(['setParam','user_details',JSON.stringify($.instance.getUserDetails())]);this.postMessage(['start']);EmbeddedForm._superClass.showFrame_.call(this,params);$.instance.setOpenedWidget(this);this.originalResizeFunction=window.onresize;var me=this;window.onresize=function(){me.updateFrameStyle_();if(me.originalResizeFunction!=undefined){me.originalResizeFunction();}}},initChat:function(chatOpenFunction){this.chatOpenFunction=chatOpenFunction;},startChat:function(cid){this.hide();if(this.chatOpenFunction!=undefined){this.chatOpenFunction(cid);}},hide:function(){window.onresize=this.originalResizeFunction;if(this.useBlocker){this.hideBlockingElement_();}
        EmbeddedForm._superClass.hide.call(this);},initBlockingElement_:function(){this.formBlockingElement=document.createElement('div');var style=this.formBlockingElement.style;style.display='none';style.position='fixed';style.zIndex=this.zIndex-1;style.top='0px';style.left='0px';style.width='100%';style.height='100%';style.backgroundColor='#000';style.opacity='0.6';style.filter='alpha(opacity = 60)';style.cursor='default';document.body.appendChild(this.formBlockingElement);try{this.originalOverflowSetting=document.body.style.overflow;if(this.originalOverflowSetting==""){this.originalOverflowSetting="auto";}}catch(e){this.originalOverflowSetting=undefined;}},hideBlockingElement_:function(){this.formBlockingElement.style.display='none';if(this.originalOverflowSetting!=undefined){try{document.body.style.overflow=this.originalOverflowSetting;}catch(e){}}},showBlockingElement_:function(){this.formBlockingElement.style.display='block';if(this.originalOverflowSetting!=undefined){try{document.body.style.overflow='hidden';}catch(e){}}},updateFrameStyle_:function(){var windowSize=this.getWindowSize_();var width=this.width;var height=this.height;if(windowSize.height>0&&windowSize.height*0.9<height){height=Math.round(windowSize.height*0.9);}
        if(windowSize.width>0&&windowSize.width*0.9<width){width=Math.round(windowSize.width*0.9);}
        width=Math.max(200,width);height=Math.max(300,height);this.postMessage(['setSize',width,height]);this.setSize(width,height);this.setZIndex(this.zIndex);this.setPosition(this.position,width,height);},getWindowSize_:function(){var size={width:800,height:600};if(document.body&&document.body.offsetWidth){size.width=document.body.offsetWidth;size.height=document.body.offsetHeight;}
        if(document.compatMode=='CSS1Compat'&&document.documentElement&&document.documentElement.offsetWidth){size.width=document.documentElement.offsetWidth;size.height=document.documentElement.offsetHeight;}
        if(window.innerWidth&&window.innerHeight){size.width=window.innerWidth;size.height=window.innerHeight;}
        return size;}});$.EmbeddedForm=EmbeddedForm;})(LiveAgent);

(function($){if($.PopupForm){return;}
    var PopupForm=$.$class({Extends:$.PopupWidget,construct:function(widgetUrl,width,height,position,specProtocol){$.PopupWidget.call(this,widgetUrl,width,height,position,specProtocol);this.url+="&ie="+encodeURIComponent(LiveAgentTrackerXD.getIeVersion());},initChat:function(chatOpenFunction){this.chatOpenFunction=chatOpenFunction;},startChat:function(cid){this.hide();if(this.chatOpenFunction!=undefined){this.chatOpenFunction(cid);}},});$.PopupForm=PopupForm;})(LiveAgent);

(function($){if($.Button){return;}
    var Button=$.$class({Extends:$.Widget,construct:function(id,element,note){$.Widget.call(this,id);this.note=note;if(this.note==undefined){this.note='';}
        var me=this;var onClose=function(){me.onCloseFunction_();}
        this.insertButtonElement_(element);this.onCloseCallBack=onClose;},initHtml:function(html){if("https:"==document.location.protocol){html=html.replace('http://','https://');}
        html=html.replace(/\{\$buttonid\}/g,this.getElementId());html=html.replace(/\{\$display\}/g,this.isBubbleClosed_()?'none':'block');this.buttonDiv.innerHTML=html;},initCss:function(css){if("https:"==document.location.protocol){css=css.replace('http://','https://');}
        css=css.replace(/\{\$buttonid\}/g,this.getElementId());var cssElement=document.createElement('style');cssElement.type='text/css';if(cssElement.styleSheet)cssElement.styleSheet.cssText=css;else cssElement.appendChild(document.createTextNode(css));document.getElementsByTagName("head")[0].appendChild(cssElement);},initEmbeddedChat:function(url,width,height,position,zIndex){this.chat=new $.EmbeddedChat(this.addButtonParamsToUrl_(url),width,height,position,zIndex,this.getElementId());},initPopoutChat:function(url,width,height,position){this.chat=new $.PopupChat(this.addButtonParamsToUrl_(url),width,height,position);},initMobileChat:function(url){this.chat=new $.PopupChat(this.addButtonParamsToUrl_(url));},initForm:function(url,width,height,position,zIndex,useBlocker,specProtocol){this.form=new $.EmbeddedForm(this.addButtonParamsToUrl_(url),width,height,position,zIndex,useBlocker,specProtocol,this.getElementId());},initMobileForm:function(url,specProtocol){this.form=new $.PopupForm(this.addButtonParamsToUrl_(url),undefined,undefined,undefined,specProtocol);},initPopoutForm:function(url,width,height,position,specProtocol){this.form=new $.PopupForm(this.addButtonParamsToUrl_(url),width,height,position,specProtocol);},initPreChatForm:function(url,width,height,position,zIndex,useBlocker){this.initForm(url,width,height,position,zIndex,useBlocker);var me=this;var openFunction=function(cid){me.hideButton_();me.chat.startChat(cid,me.onCloseCallBack);}
        this.form.initChat(openFunction);},initPopoutPreChatForm:function(url,width,height,position,specProtocol){this.form=new $.PopupForm(this.addButtonParamsToUrl_(url),width,height,position,specProtocol);var me=this;var openFunction=function(cid){me.hideButton_();me.chat.startChat(cid,me.onCloseCallBack);}
        this.form.initChat(openFunction);},initPreChatMobileForm:function(url){this.initMobileForm(url);var me=this;var openFunction=function(cid){me.hideButton_();me.chat.startChat(cid,me.onCloseCallBack);}
        this.form.initChat(openFunction);},initVideoCallForm:function(url,width,height,zIndex){this.form=new $.VideoCallForm(this.addButtonParamsToUrl_(url),width,height,zIndex,this.getElementId());},initCallPopOut:function(url,width,height,centeredWindow){if(centeredWindow=='Y'){this.form=new $.PopupForm(this.addButtonParamsToUrl_(url),width,height,'C','https:');}else{this.form=new $.PopupForm(this.addButtonParamsToUrl_(url),undefined,undefined,undefined,'https:');}},initVideoCallPopOut:function(url,centeredWindow){var windowSize=$.instance.getWindowSize_();this.initCallPopOut(url,Math.round(windowSize.width*0.9),Math.round(windowSize.height*0.9),centeredWindow);},initVideoCall:function(url,width,height,zIndex,centeredWindow){if(document.location.href.indexOf("https://")==0){this.initVideoCallForm(url+'&cwt=phone_popup',width,height,zIndex);return;}
        this.initVideoCallPopOut(url+'&cwt=phone_popout',centeredWindow);},initVoiceCallForm:function(url,width,height,zIndex){this.initForm(url,width,height,'C',zIndex,true,'https:');},initVoiceCallPopOut:function(url,width,height,centeredWindow){this.initCallPopOut(url,width,height,centeredWindow);},initVoiceCall:function(url,width,height,zIndex,centeredWindow){if(document.location.href.indexOf("https://")==0){this.initVoiceCallForm(url+'&cwt=phone_popup',width,height,zIndex);return;}
        this.initVoiceCallPopOut(url+'&cwt=phone_popout',width,height,centeredWindow);},isBubbleClosed_:function(){var closedBubbleButtons=$.getCookie('closedBubbleButtons');return closedBubbleButtons.indexOf(this.id)!=-1;},closeBubble:function(){if(this.isBubbleClosed_()){return;}
        var closedBubbleButtons=$.getCookie('closedBubbleButtons');closedBubbleButtons+=','+this.id;$.setCookie("closedBubbleButtons",closedBubbleButtons,60);},insertButtonElement_:function(element){this.buttonDiv=document.createElement('div');this.buttonDiv.setAttribute('id',this.getElementId());var me=this;this.buttonDiv.onclick=function(){me.onClick();};this.buttonDiv.onmouseout=function(){me.onMouseOut();};this.buttonDiv.style.cursor='pointer';this.buttonDiv.className+=this.getElementId()+'-animate';element.parentNode.insertBefore(this.buttonDiv,element.nextSibling);element.parentNode.removeChild(element);},getCreateRequest:function(){var request=Button._superClass.getCreateRequest.call(this);if(this.isMSIE9orLower_()){request.add('ie9',"Y");}
        return request;},isMSIE9orLower_:function(){if(!window.opera&&/MSIE\s(\d+\.\d+);/.test(navigator.userAgent)){var ieVer=new Number(RegExp.$1)
        if(ieVer<9.0){return true;}}
        return false;},hideButton_:function(){if(typeof this.buttonDiv!=='undefined'&&this.buttonDiv!=null){this.buttonDiv.style.visibility='hidden';this.buttonDiv.className=" ";}},onCloseFunction_:function(){if(typeof this.buttonDiv!=='undefined'&&this.buttonDiv!=null){this.buttonDiv.style.visibility='visible';this.buttonDiv.className+=this.getElementId()+'-animate';}},onClick:function(){if($.instance.hasOpenedWidget()){return;}
        this.hideButton_();if(this.form!=null){this.form.show({note:this.note},this.onCloseCallBack);return;}
        this.chat.show({note:this.note},this.onCloseCallBack);},onMouseOut:function(){if(typeof this.buttonDiv!=='undefined'&&this.buttonDiv!=null){this.buttonDiv.className=" ";}},onOnline:function(){},onOffline:function(){}});$.Button=Button;})(LiveAgent);

(function($){if($.VirtualButton){return;}
    var VirtualButton=$.$class({Extends:$.Button,construct:function(id,element,note){$.Button.call(this,id,element,note);},insertButtonElement_:function(element){},getCreateRequest:function(){var request=VirtualButton._superClass.getCreateRequest.call(this);request.add('v','Y');return request;},initHtml:function(html){},initCss:function(css){},getElementId:function(){return this.id;},hideButton_:function(){},onCloseFunction_:function(){}});$.VirtualButton=VirtualButton;})(LiveAgent);

(function($){if($.InPageForm){return;}
    var InPageForm=$.$class({Extends:$.Widget,construct:function(id,element,note){$.Widget.call(this,id);this.note=note;if(this.note==undefined){this.note='';}
        this.init_(element);},resize:function(width,height){var style=this.iframeElement.style;style.width=width+"px";style.height=height+"px";},initForm:function(url,width,height){this.iframeElement.setAttribute('src',$.instance.getServerUrl()+url
        +"&pt="+encodeURIComponent(document.title)
        +((this.note!=undefined&&this.note!='')?'&note='+escape(this.note):'')
        +"&vid="+$.instance.getBrowserId()
        +"&ud="+encodeURIComponent(JSON.stringify($.instance.getUserDetails()))
        +"&eid="+this.getElementId()
        +"#"+encodeURIComponent(document.location.href));this.resize(width,height);},init_:function(element){this.iframeElement=document.createElement('iframe');this.iframeElement.setAttribute('id',this.getElementId());var style=this.iframeElement.style;style.maxWidth="100%";style.width="0px";style.height="0px";style.overflow='hidden';style.border='0 none transparent';element.parentNode.insertBefore(this.iframeElement,element.nextSibling);element.parentNode.removeChild(element);},getCreateRequest:function(){var request=InPageForm._superClass.getCreateRequest.call(this);request.add('t','I');return request;}});$.InPageForm=InPageForm;})(LiveAgent);

(function($){if($.KbSearchWidget){return;}
    var KbSearchWidget=$.$class({Extends:$.Widget,construct:function(id){this.className="i-kb-search";this.kbsid="ik"+id;$.Widget.call(this,id);},initKbSearch:function(url,width,height,position,zIndex){this.iframe=new $.Iframe($.instance.getServerUrl()+url+"?id="+this.id+"&eid="+this.getElementId()+"&t="+this.dateChanged+"#"+encodeURIComponent(document.location.href));this.iframe.setPosition(position,width,height);this.iframe.setSize(width,height);if(zIndex==undefined||zIndex.trim()==""){zIndex='999997';}
        this.iframe.setZIndex(zIndex);this.iframe.show();if(typeof this.className!=="undefined"){this.iframe.getElement().setAttribute('class',this.className);}
        if(typeof this.id!=="undefined"){this.iframe.getElement().setAttribute('id',this.kbsid);}},resize:function(width,height){this.iframe.setSize(width,height);},close:function(){this.iframe.hide();},getCreateRequest:function(){var request=KbSearchWidget._superClass.getCreateRequest.call(this);request.add('t','KS');return request;}});$.KbSearchWidget=KbSearchWidget;})(LiveAgent);

(function($){if($.Invitation){return;}
    var Invitation=$.$class({Extends:$.Button,construct:function(id,timeOnPage){this.timeOnPage=timeOnPage;this.id=id;this.elementId=this.buildElementId(id);$.Button.call(this,id);},buildElementId:function(id){return"b_"+id+"_"+Math.round((Math.random()*1000)).toString();},initHtml:function(html){this.buttonDiv=document.createElement('div');this.buttonDiv.setAttribute('id',this.getElementId());html=html.replace(/\{\$open\}/g,this.params.openCommand);html=html.replace(/\{\$close\}/g,this.params.closeCommand);html=html.replace(/\{\$agentName\}/g,this.params.agentName);html=html.replace(/\{\$agentFirstName\}/g,this.params.agentName.split(' ')[0]);html=html.replace(/\{\$agentLastName\}/g,this.params.agentName.split(' ').length>1?this.params.agentName.split(' ')[1]:this.params.agentName.split(' ')[0]);html=html.replace(/\{\$agentAvatarUrl\}/g,this.params.avatarUrl.replace("__BASE_URL__",$.instance.getServerUrl()));html=html.replace(/\{\$agentAvatarBackgroundUrl\}/g,this.params.avatarBackgroundUrl.replace("__BASE_URL__",$.instance.getServerUrl()));this.buttonDiv.innerHTML=html;document.body.appendChild(this.buttonDiv);if(this.params.animation=='Y'){this.animate_(1000,1);}else{this.setStyle_(100);}},initInvitation:function(params){if(params.openCommand==undefined){params.openCommand="LiveAgent.instance.getWidget('"+this.getElementId()+"').open()";}
        if(params.closeCommand==undefined){params.closeCommand="LiveAgent.instance.getWidget('"+this.getElementId()+"').refuse()";}
        if(params.verticalConstant==undefined){params.verticalConstant=0;}
        if(params.horizontalConstant==undefined){params.horizontalConstant=0;}
        if(params.zIndex==undefined||params.zIndex.trim()==""){params.zIndex='999997';}
        this.params=params;var me=this;setTimeout(function(){me.close();},params.validity*1000);},open:function(){this.onClick();this.close();},refuse:function(){this.close();var closedInvitations=$.getCookie("closedInvitations");if(closedInvitations!=null&&closedInvitations!=""){closedInvitations+=','+this.id;}else{closedInvitations=this.id;}
        $.setCookie("closedInvitations",closedInvitations);var request=new $.Request('RefuseInvitation');$.instance.send(request);},close:function(){if(typeof this.buttonDiv!=='undefined'&&this.buttonDiv!=null&&this.buttonDiv.parentNode!=null){this.buttonDiv.parentNode.removeChild(this.buttonDiv);}},sendInitRequest_:function(){var me=this;this.sendTimer=setTimeout(function(){$.instance.send(me.getCreateRequest());},this.getTimeToInit_());},getTimeToInit_:function(){var timeToInit=$.instance.getPageOpenedTimestamp()+this.timeOnPage*1000-new Date().getTime();if(timeToInit>0){return timeToInit;}
        return 1;},cancel:function(){clearTimeout(this.sendTimer);},insertButtonElement_:function(element){},animate_:function(time,step){this.setStyle_(step);if(step<100){var me=this;setTimeout(function(){me.animate_(time,step+1);},time/100);}},setStyle_:function(step){if(typeof this.buttonDiv==='undefined'||this.buttonDiv==null){return;}
        this.buttonDiv.style.position='fixed';this.buttonDiv.style.zIndex=this.params.zIndex;var xAnimation=(step%2==0?1:-1)*(-this.params.height/25+this.params.height/100*step/25);if(this.paramsposition=='O'){var cursor=$.instance.getCursorPosition();var scrollPosition=this.getScrollXY();this.buttonDiv.style.top=cursor.y-scrollPosition.y+this.params.verticalConstant+'px';this.buttonDiv.style.left=Math.round(cursor.x-scrollPosition.x+xAnimation)+this.params.horizontalConstant+'px';return;}
        switch(this.params.position){case'TLR':this.buttonDiv.style.left='0';this.buttonDiv.style.right='0';this.buttonDiv.style.top=Math.round(-this.params.height+this.params.height/100*step)+this.params.verticalConstant+'px';return;case'BLR':this.buttonDiv.style.left='0';this.buttonDiv.style.right='0';this.buttonDiv.style.bottom=Math.round(-this.params.height+this.params.height/100*step)+this.params.verticalConstant+'px';return;}
        switch(this.params.position[0]){case'T':this.buttonDiv.style.top=Math.round(-this.params.height+this.params.height/100*step)+this.params.verticalConstant+'px';break;case'B':this.buttonDiv.style.bottom=Math.round(-this.params.height+this.params.height/100*step)+this.params.verticalConstant+'px';break;case'C':this.buttonDiv.style.top='50%';this.buttonDiv.style.marginTop=Math.round(-this.params.height/2)+'px';break;}
        switch(this.params.position[1]){case'L':this.buttonDiv.style.left=Math.round(-this.params.width+this.params.width/100*step)+this.params.horizontalConstant+'px';break;case'R':this.buttonDiv.style.right=Math.round(-this.params.width+this.params.width/100*step)+this.params.horizontalConstant+'px';break;case'C':this.buttonDiv.style.left='50%';this.buttonDiv.style.marginLeft=Math.round(-this.params.width/2)+'px';break;default:this.buttonDiv.style.left='50%';this.buttonDiv.style.marginLeft=Math.round(-this.params.width/2+xAnimation)+'px';break;}},getScrollXY:function(){if(typeof(window.pageYOffset)=='number'){return{x:window.pageXOffset,y:window.pageYOffset};}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){return{x:document.body.scrollLeft,y:document.body.scrollTop};}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){return{x:document.documentElement.scrollLeft,y:document.documentElement.scrollTop}}
        return{x:0,y:0};},getElementId:function(){return this.elementId;}});$.Invitation=Invitation;})(LiveAgent);

(function($){if($.ManualInvitation){return;}
    var ManualInvitation=$.$class({Extends:$.Button,construct:function(id,cid){$.Button.call(this,id);this.cid=cid;},initHtml:function(html){},initCss:function(css){},initEmbeddedChat:function(url,width,height,position,zIndex){this.chat=new $.EmbeddedChat(this.addButtonParamsToUrl_(url),width,height,position,zIndex);this.chat.autoPrepareNextFrame=false;var widgetId=this.id;this.chat.addOnCloseFunction(function(){LiveAgent.instance.removeWidget(widgetId);});},addButtonParamsToUrl_:function(url){url=ManualInvitation._superClass.addButtonParamsToUrl_.call(this,url);return url+"&cid="+this.cid+'&fi=Y';},open:function(){this.onClick();},sendInitRequest_:function(){},insertButtonElement_:function(element){this.buttonDiv=document.createElement('div');this.buttonDiv.setAttribute('id',this.getElementId());},getElementId:function(){return this.id;}});$.ManualInvitation=ManualInvitation;})(LiveAgent);

(function($){if($.TrackDb){return;}
    var UpdateVisit=$.$class({Extends:$.Request,construct:function(timeOnPage){$.Request.call(this,'UpdateVisit');this.add('t',timeOnPage);}});var TrackDb=$.$class({construct:function(trackingTimeout){this.timer=false;this.startTime=new Date();this.setTrackingTimeout_(trackingTimeout);this.scheduleTrack_();},setTrackingTimeout:function(timeout){this.setTrackingTimeout_(timeout);if(this.trackingTimeout<0){clearTimeout(this.timer);return;}
        this.scheduleTrack_();},scheduleTrack_:function(){clearTimeout(this.timer);var that=this;this.timer=setTimeout(function(){that.track()},this.trackingTimeout);},getTimeOnPageMin_:function(){return Math.floor((new Date().getTime()-this.startTime)/60000);},sendBusRequest:function(){$.instance.send(new $.Request('DbBus'));},track:function(){$.instance.send(new UpdateVisit(this.getTimeOnPageMin_()));this.sendBusRequest();this.scheduleTrack_();},setTrackingTimeout_:function(timeout){this.trackingTimeout=timeout*1000;}});$.TrackDb=TrackDb;})(LiveAgent);

(function($){if($.TrackFile){return;}
    var FileBusConfirm=$.$class({Extends:$.Request,construct:function(lastId){$.Request.call(this,'FileBusConfirm');this.add('lastId',lastId);}});var TrackFile=$.$class({Extends:$.TrackDb,construct:function(trackingTimeout,busTimeout){this.lastEventId=-1;var lastEventIdCookie=$.getCookie("laEventId");if(lastEventIdCookie!=null&&lastEventIdCookie!=""){this.lastEventId=lastEventIdCookie;}
        this.setFileBusTimeout_(busTimeout);$.TrackDb.call(this,trackingTimeout);this.scheduleReadBus_();},setFileBusTimeout:function(timeout){this.setFileBusTimeout_(timeout);if(this.busTimeout<0){clearTimeout(this.busTimer);return;}
        this.scheduleReadBus_();},processEvent:function(id,event){if(id<=this.lastEventId){return;}
        eval(event);this.lastEventId=id;$.setCookie("laEventId",id,"");clearTimeout(this.flushTimer);var me=this
        setTimeout(function(){me.flushEvents()},500);},scheduleReadBus_:function(){clearTimeout(this.busTimer);var that=this;this.busTimer=setTimeout(function(){that.readBus_()},this.busTimeout);},readBus_:function(){$.instance.addScript("accounts/default1/cache/bus/"+$.instance.getSessionId()+".js?r="
        +Math.floor(Math.random()*10000));this.scheduleReadBus_();},setFileBusTimeout_:function(timeout){this.busTimeout=timeout*1000;},sendBusRequest:function(){},flushEvents:function(){$.instance.send(new FileBusConfirm(this.lastEventId));}});$.TrackFile=TrackFile;})(LiveAgent);

(function($){if($.TrackPushStream){return;}
    var TrackPushStream=$.$class({Extends:$.Iframe,construct:function(version,channelPreffix,tenantId,visitorBusDomain){var params={'location':document.location.href,'b':LiveAgent.instance.getBrowserId(),'t':tenantId};var domain=visitorBusDomain;if(domain==undefined||domain==''){domain=$.instance.getServerUrl();}
        $.Iframe.call(this,domain+'scripts/lib/bus.html?v='
            +version+'#'+encodeURIComponent(LiveAgent.stringifyToJSON(params)));var channel=channelPreffix+$.instance.getSessionId();this.show({channel:channel});},showFrame_:function(params){this.postMessage(['start',params.channel]);},processEvent:function(event){eval(event);}});$.TrackPushStream=TrackPushStream;})(LiveAgent);

(function($){if($.KbChat){return;}
    var KbChat=$.$class({Extends:$.Widget,construct:function(id,cid){$.Widget.call(this,id);this.cid=cid;},initEmbeddedChat:function(url,width,height,position,zIndex){this.chat=new $.EmbeddedChat(this.addButtonParamsToUrl_(url),width,height,position,zIndex);},initMobileChat:function(url){this.chat=new $.PopupChat(this.addButtonParamsToUrl_(url));},buildElementId:function(id){return id;},getCreateRequest:function(){var request=KbChat._superClass.getCreateRequest.call(this);request.add('t','KC');request.add('v','Y');return request;},startChat:function(){if($.instance.hasOpenedWidget()){return;}
        this.chat.show({kbChatCid:this.cid});}});$.KbChat=KbChat;})(LiveAgent);

(function($){if($.RemoteAuth){return;}
    var RemoteAuth=$.$class({construct:function(authHash,action){this.url=$.instance.getServerUrl()+"scripts/apiAuthUser.php?ahash="+
        encodeURIComponent(authHash)+"&act="+encodeURIComponent(action)+"&t="+encodeURIComponent(new Date().getTime());},show:function(){this.element=document.createElement('iframe');var me=this;var onLoadFunction=function(){me.onLoad_();}
        if(this.element.attachEvent){this.element.attachEvent('onload',onLoadFunction);}else{this.element.onload=onLoadFunction;}
        var style=this.element.style;style.width='1px';style.height='1px';style.cssFloat='left';style.left='-1000px';this.element.setAttribute('src',this.url);document.body.appendChild(this.element);},hide:function(){document.body.removeChild(this.element);},onLoad_:function(){var me=this;setTimeout(function(){me.hide();},5000);}});RemoteAuth.login=function(authHash){var iframe=new RemoteAuth(authHash,'login');iframe.show();};RemoteAuth.logout=function(authHash){var iframe=new RemoteAuth(authHash,'logout');iframe.show();};$.RemoteAuth=RemoteAuth;})(LiveAgent);

(function($){if($.VideoCallForm){return;}
    var VideoCallForm=$.$class({Extends:$.EmbeddedForm,construct:function(widgetUrl,width,height,zIndex,cwid){$.EmbeddedForm.call(this,widgetUrl,width,height,'',zIndex,'true','https:',cwid);},updateFrameStyle_:function(){var windowSize=this.getWindowSize_();var width=Math.round(windowSize.width*0.9);var height=Math.round(windowSize.height*0.9);width=Math.max(200,width);height=Math.max(300,height);this.postMessage(['setSize',width,height]);this.setSize(windowSize.width,windowSize.height);this.element.style.top='0px';this.element.style.left='0px';this.setZIndex(this.zIndex);}});$.VideoCallForm=VideoCallForm;})(LiveAgent);